# Generated by Django 5.2.7 on 2025-10-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
